- hosts: localhost
  connection: local
  vars_prompt:
    - name: ansible_become_password
      prompt: Enter sudo pw
      private: yes

  vars:
    helm_url: https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
    terraform_url: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
    tflint_url: https://github.com/terraform-linters/tflint/releases/download/v0.24.1/tflint_linux_amd64.zip

  roles:
    - local-setup
  become: yes
