- hosts: localhost
  connection: local
  vars_prompt:
    - name: ansible_become_password
      prompt: Enter sudo pw
      private: yes

  roles:
    - local-setup
  become: yes
  #ansible_become_password: "{{ sudo_pw }}"
